spring.application.name=aci
# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://imran:imran123@aci-cluster.zmlet3k.mongodb.net/session_db

# Server Port (Aapne 8082 decide kiya tha)
server.port=8082

# Optional: Logs dekhne ke liye (Ki queries sahi ja rahi hain ya nahi)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
